owner: FP-Design-Code # Your GitHub organization or username, where this repository lives
repo: ded-uptime # The name of this repository

sites:
  - name: Server
    url: https://ded.floating-point.com

status-website:
  name: Uptime | Floating-Point
  cname: uptime.floating-point.com
  introTitle: "Current status of **Floating-Point's** server."
  theme: dark
  logoUrl: https://status.floating-point.com/uptime/icon.svg
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://floating-point.com
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
